name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pyinstaller pyautogui pyscreeze pytweening mouseinfo

    - name: Build EXE (PowerShell格式)
      run: |
        pyinstaller --onefile --noconsole --name "GUI_Locator" `
          --hidden-import pyautogui `
          --hidden-import pyscreeze `
          --hidden-import pytweening `
          --hidden-import mouseinfo `
          --collect-data pyautogui `
          gui_locator_multi.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: GUI_Locator
        path: dist/GUI_Locator.exe
