name: Build EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-latest
    timeout-minutes: 30  # 增加超时时间

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # 推荐使用更新的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas openpyxl pillow
        # 使用 requirements.txt 更佳
        # pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --name "GUI_Locator" gui_locator_multi.py
        # 如需添加资源文件
        # pyinstaller --onefile --noconsole --add-data "assets/*;assets" --name "GUI_Locator" gui_locator_multi.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4  # 使用最新 v4 版本
      with:
        name: gui-locator-exe
        path: dist/GUI_Locator.exe
        retention-days: 7  # 自动清理旧构建
