name: Build EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # 必须使用 Windows 环境打包 EXE

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # 添加你的其他依赖（根据 requirements.txt 或手动指定）
        pip install pandas openpyxl pillow  # 示例依赖

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --name "GUI_Locator" gui_locator_multi.py
        # 可选：添加图标 --icon=app.ico
        # 可选：添加数据文件 --add-data "assets;assets"

    - name: Archive EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: gui-locator-exe
        path: dist/GUI_Locator.exe
